### ISSUE TITLE
Persisting multiple directories using `[[persist]]`

### ISSUE THREAD

**Issue by raryanpur** [silitics/rugpi#22]
Is it possible to specify multiple directories using `[[persist]]` and `directory`? Maybe as follows?

```
[[persist]]
directory=/root
directory=/somethinglese
```

or

```
[[persist]]
directory=/root

[[persist]]
directory=/somethingelse
```

**Comment by koehlma** [comment]
Yes, the latter should work as it is the way to do “arrays of tables” in TOML.
